create table if not exists public.site_pageviews (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  visitor_id uuid not null,
  session_id uuid not null,
  user_id uuid references auth.users(id) on delete set null,
  path text not null check (char_length(path) between 1 and 300),
  page_title text,
  referrer_host text,
  traffic_source text not null default 'Direto',
  device_category text not null default 'Outro' check (device_category in ('Celular','Computador','Tablet','Outro'))
);

create index if not exists site_pageviews_occurred_at_idx on public.site_pageviews (occurred_at desc);
create index if not exists site_pageviews_visitor_idx on public.site_pageviews (visitor_id, occurred_at desc);
create index if not exists site_pageviews_session_idx on public.site_pageviews (session_id, occurred_at desc);
create index if not exists site_pageviews_path_idx on public.site_pageviews (path, occurred_at desc);
create index if not exists site_pageviews_source_idx on public.site_pageviews (traffic_source, occurred_at desc);
create index if not exists site_pageviews_device_idx on public.site_pageviews (device_category, occurred_at desc);

alter table public.site_pageviews enable row level security;
revoke all on table public.site_pageviews from anon, authenticated;

create or replace function public.record_site_pageview(
  p_visitor_id uuid,
  p_session_id uuid,
  p_path text,
  p_page_title text default null,
  p_referrer_host text default null,
  p_traffic_source text default 'Direto',
  p_device_category text default 'Outro'
)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_uid uuid := auth.uid();
  v_path text := left(coalesce(nullif(trim(p_path), ''), '/'), 300);
  v_title text := nullif(left(trim(coalesce(p_page_title, '')), 200), '');
  v_referrer text := nullif(left(lower(trim(coalesce(p_referrer_host, ''))), 160), '');
  v_source text := coalesce(nullif(left(trim(coalesce(p_traffic_source, '')), 50), ''), 'Direto');
  v_device text := case
    when p_device_category in ('Celular','Computador','Tablet','Outro') then p_device_category
    else 'Outro'
  end;
begin
  if p_visitor_id is null or p_session_id is null then
    return;
  end if;

  if v_path like '/admin%' then
    return;
  end if;

  if exists (
    select 1
    from public.site_pageviews
    where visitor_id = p_visitor_id
      and session_id = p_session_id
      and path = v_path
      and occurred_at > now() - interval '5 seconds'
  ) then
    return;
  end if;

  insert into public.site_pageviews (
    visitor_id, session_id, user_id, path, page_title, referrer_host, traffic_source, device_category
  ) values (
    p_visitor_id, p_session_id, v_uid, v_path, v_title, v_referrer, v_source, v_device
  );
end;
$$;

revoke all on function public.record_site_pageview(uuid, uuid, text, text, text, text, text) from public;
grant execute on function public.record_site_pageview(uuid, uuid, text, text, text, text, text) to anon, authenticated;

create or replace function public.get_site_analytics(p_days integer default 30)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_uid uuid := auth.uid();
  v_days integer := greatest(1, least(coalesce(p_days, 30), 365));
  v_today date := (now() at time zone 'America/Sao_Paulo')::date;
  v_start date;
  v_result jsonb;
begin
  if v_uid is null or not exists (
    select 1 from public.profiles where id = v_uid and role = 'admin'
  ) then
    raise exception 'ADMIN_REQUIRED' using errcode = '42501';
  end if;

  v_start := v_today - (v_days - 1);

  with period_events as (
    select *, (occurred_at at time zone 'America/Sao_Paulo')::date as local_date
    from public.site_pageviews
    where (occurred_at at time zone 'America/Sao_Paulo')::date between v_start and v_today
  ),
  period_visitors as (
    select visitor_id, bool_or(user_id is not null) as authenticated
    from period_events
    group by visitor_id
  ),
  first_seen as (
    select visitor_id, min((occurred_at at time zone 'America/Sao_Paulo')::date) as first_date
    from public.site_pageviews
    group by visitor_id
  ),
  daily_agg as (
    select local_date, count(*) as views, count(distinct visitor_id) as visitors, count(distinct session_id) as sessions
    from period_events
    group by local_date
  ),
  days as (
    select generate_series(v_start::timestamp, v_today::timestamp, interval '1 day')::date as d
  ),
  page_rows as (
    select path,
           coalesce(max(page_title) filter (where page_title is not null), 'Sem título') as title,
           count(*) as views,
           count(distinct visitor_id) as visitors
    from period_events
    group by path
    order by views desc, visitors desc, path
    limit 10
  ),
  source_rows as (
    select traffic_source as source,
           count(distinct session_id) as sessions,
           count(distinct visitor_id) as visitors
    from period_events
    group by traffic_source
    order by sessions desc, visitors desc
    limit 10
  ),
  device_rows as (
    select device_category as device,
           count(distinct visitor_id) as visitors,
           count(*) as views
    from period_events
    group by device_category
    order by visitors desc, views desc
  )
  select jsonb_build_object(
    'period', jsonb_build_object('days', v_days, 'start', v_start, 'end', v_today),
    'overview', jsonb_build_object(
      'visitors', (select count(*) from period_visitors),
      'sessions', (select count(distinct session_id) from period_events),
      'views', (select count(*) from period_events),
      'newVisitors', (select count(*) from first_seen where first_date between v_start and v_today),
      'returningVisitors', greatest(
        (select count(*) from period_visitors) - (select count(*) from first_seen where first_date between v_start and v_today),
        0
      ),
      'authenticatedVisitors', (select count(*) from period_visitors where authenticated),
      'anonymousVisitors', (select count(*) from period_visitors where not authenticated)
    ),
    'realtime', jsonb_build_object(
      'activeVisitors', (
        select count(distinct visitor_id)
        from public.site_pageviews
        where occurred_at >= now() - interval '10 minutes'
      )
    ),
    'daily', coalesce((
      select jsonb_agg(jsonb_build_object(
        'date', to_char(days.d, 'YYYY-MM-DD'),
        'views', coalesce(daily_agg.views, 0),
        'visitors', coalesce(daily_agg.visitors, 0),
        'sessions', coalesce(daily_agg.sessions, 0)
      ) order by days.d)
      from days
      left join daily_agg on daily_agg.local_date = days.d
    ), '[]'::jsonb),
    'pages', coalesce((
      select jsonb_agg(jsonb_build_object('path', path, 'title', title, 'views', views, 'visitors', visitors) order by views desc, visitors desc)
      from page_rows
    ), '[]'::jsonb),
    'sources', coalesce((
      select jsonb_agg(jsonb_build_object('source', source, 'sessions', sessions, 'visitors', visitors) order by sessions desc, visitors desc)
      from source_rows
    ), '[]'::jsonb),
    'devices', coalesce((
      select jsonb_agg(jsonb_build_object('device', device, 'visitors', visitors, 'views', views) order by visitors desc, views desc)
      from device_rows
    ), '[]'::jsonb),
    'generatedAt', now()
  ) into v_result;

  return v_result;
end;
$$;

revoke all on function public.get_site_analytics(integer) from public;
revoke execute on function public.get_site_analytics(integer) from anon;
grant execute on function public.get_site_analytics(integer) to authenticated;
